name: 日本語→英語に翻訳して_en.mdファイルを作成する
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: curlとpythonとpipをインストール
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install curl git python3
          
      - name: pipパッケージ(requests multiprocessing googletrans)をインストール
        run: |
          python3 -m pip install --upgrade pip
          pip install requests
          pip install git+https://github.com/alainrouillon/py-googletrans@feature/enhance-use-of-direct-api
          
      - name: curlを実行
        run: curl -sf https://raw.githubusercontent.com/shimajima-eiji/__Operation-Maintenance/main/for_Development/googletrans.py | python3
        
#       # 翻訳した場合のみ処理する
#       - name: Commitとpush
#         run: |
#           if [ $(tail -n 1 translate.log) -ne 0 ]
#           then
#             rm translate.log  # 先にログファイルを消さないと、ログファイルもpushしてしまう
#             git config --global user.email "${{ secrets.EMAIL }}"
#             git config --global user.name "shimajima-eiji"
#             git add -A
#             git commit -m "[Update]translated ja -> en: by Github Actions"
#             git pull
#             git push
#             echo "[COMPLETE] translate."
#           else
#             echo "[SKIP] No translate."
#           fi   
